// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQTo-OrPzu6sgIlNdwOwfxl7yWhxSniJM',
    appId: '1:264435704665:web:8c2b74c94871aac8c7a248',
    messagingSenderId: '264435704665',
    projectId: 'dewbet-jkfn88',
    authDomain: 'dewbet-jkfn88.firebaseapp.com',
    storageBucket: 'dewbet-jkfn88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92LDQMf9_yI9Qm8C8Uu9zfwmu1y2QUN8',
    appId: '1:264435704665:android:2bdb261b8a9866c9c7a248',
    messagingSenderId: '264435704665',
    projectId: 'dewbet-jkfn88',
    storageBucket: 'dewbet-jkfn88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-3hDLmZxc2d6zJxYa42GdXQoGvp8TKaw',
    appId: '1:264435704665:ios:770eebc051a699a8c7a248',
    messagingSenderId: '264435704665',
    projectId: 'dewbet-jkfn88',
    storageBucket: 'dewbet-jkfn88.appspot.com',
    iosBundleId: 'com.example.binanceDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-3hDLmZxc2d6zJxYa42GdXQoGvp8TKaw',
    appId: '1:264435704665:ios:770eebc051a699a8c7a248',
    messagingSenderId: '264435704665',
    projectId: 'dewbet-jkfn88',
    storageBucket: 'dewbet-jkfn88.appspot.com',
    iosBundleId: 'com.example.binanceDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQTo-OrPzu6sgIlNdwOwfxl7yWhxSniJM',
    appId: '1:264435704665:web:8fed86118ad8354fc7a248',
    messagingSenderId: '264435704665',
    projectId: 'dewbet-jkfn88',
    authDomain: 'dewbet-jkfn88.firebaseapp.com',
    storageBucket: 'dewbet-jkfn88.appspot.com',
  );

}